### ISSUE TITLE
SendCloudRequestException: An error occurred while fetching shipping methods from the Sendcloud API.

### ISSUE THREAD

**Issue by jornwildenbeest** [white-nl/commerce-sendcloud#8]
Once in a while the plugin throws the following error: SendCloudRequestException.

Info from the log files:

```
2022-05-17 11:03:07 [-][1][c6kvuhpd9rmcqbfjimn6vi5osc][error][JouwWeb\SendCloud\Exception\SendCloudRequestException] GuzzleHttp\Exception\ServerException: Server error: `GET https://panel.sendcloud.sc/api/v2/shipping_methods?sender_address=all` resulted in a `502 Bad Gateway` response:
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html> (truncated...)
```

```
Next JouwWeb\SendCloud\Exception\SendCloudRequestException: An error occurred while fetching shipping methods from the Sendcloud API. in /Users/jorn/Sites/site/vendor/jouwweb/sendcloud/src/Client.php:668
Stack trace:
#0 /Users/jorn/Sites/site/vendor/jouwweb/sendcloud/src/Client.php(148): JouwWeb\SendCloud\Client->parseGuzzleException(Object(GuzzleHttp\Exception\ServerException), 'An error occurr...')
#1 /Users/jorn/Sites/site/vendor/white-nl/commerce-sendcloud/src/client/JouwWebSendcloudAdapter.php(152): JouwWeb\SendCloud\Client->getShippingMethods()
#2 /Users/jorn/Sites/site/vendor/white-nl/commerce-sendcloud/src/variables/SendcloudVariable.php(66): white\commerce\sendcloud\client\JouwWebSendcloudAdapter->getShippingMethods()
#3 /Users/jorn/Sites/site/vendor/twig/twig/src/Extension/CoreExtension.php(1566): white\commerce\sendcloud\variables\SendcloudVariable->getShippingMethods()
#4 /Users/jorn/Sites/site/vendor/craftcms/cms/src/helpers/Template.php(106): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(white\commerce\sendcloud\variables\SendcloudVariable), 'getShippingMeth...', Array, 'method', false, false)
```

Sometimes it works with the next reload, sometimes you have to wait a couple seconds..

I think the biggest problem is that it is throwing this big error so the whole checkout becomes unavailable.

Is there anything we can do to fix this?

**Comment by WHITE-developer** [comment]
Hi @jornwildenbeest ,
We just released an update which adds some caching to the getShippingMethods() function.
This way we don't need to always use the Sendcloud API to query for the available shipping methods.
